name: Vault add-on
version: "0.4.0"
slug: vault
description: Vault add-on
url: "https://github.com/dchauviere/hassio-addons/tree/main/vault"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
ports:
  8200/tcp: 8200
map:
  - ssl:rw
image: "dawei06/{arch}-hassio-vault"
backup: "cold"
webui: https://[HOST]:[PORT:8200]/
watchdog: https://[HOST]:[PORT:8200]/
hassio_api: true
options:
  init:
    login: admin
    password: admin
    ca_common_name: My CA
    domain: lan
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  init:
    login: str
    password: str
    ca_common_name: str
    domain: str
  certfile: str
  keyfile: str
